import random
import os

''' How to...

Go to the end end insert the questions like you see in lista_domande

you can put more possible answers using #

you can add a list of possible answer in the question with #

'''

def add_questions(lista_domande):
	''' creates a string with all call to input with questions and answer to be shown '''

	inp = ""
	for d in lista_domande:
		if "#" in d[0]:
			question = d[0].split("#")[0]
			possible = d[0].split("#")[1:]
			possible = "[" + ",".join(possible) + "]"
			inp += f"""input("{question}<br>{possible}", "{d[1]}");\n"""
		else:
			inp += f"""input("{d[0]}", "{d[1]}");\n"""

	return inp


def start():
	html = """
	<style>
		.fontbig {
			font-size: 1.5em;
		}
	 
	body, html {
	 background: #ECEDEF;
	 margin-left: 10%;
	 margin-right: 10%;
	 padding: 0;
	}
	 

	</style>
	<html oncontextmenu="return false;">
	<script>

	// ======================== CHECK ======================= >
	const rightcolor = 'yellow'
	const wrongcolor = "red";

	function check(inp_text, giusta){
		// giusta is "1#2#3" and is splitted into a list of strings, then check if in this list there is the user input 
		let lista_esatte = giusta.split("#"); // right answers
		let user_input = inp_text.value;       // user input
		if (lista_esatte.includes(user_input.toLowerCase())){
			// Right Answer = yellow background
			inp_text.style.background = rightcolor; // turns yellow if right
			return inp_text.value;
		}
		else{
			// Wrong Answer = red background
			inp_text.style.background = wrongcolor; // turn red if wrong
		}
	} // ====================================== CHECK === !

	var countdom = 1;

	function input(domanda, giusta){
		var dom_h2 = "<table style='background:#fcab41;'><td><p class='fontbig' style='color: blue'>" + countdom++ + " " + domanda;

		var part1 = dom_h2 + "<br><i style='color:red'>Answer and press return</i><br><input id='casella' class='fontbig' type=text class='t1' placeholder='?...' onchange=\\"if (check(this,'";
		
		part1 += giusta + "'));\\" style='text-align:right'/></center></p></table>";
		
		document.write(part1);
		}
		
	</script>
	<!--         Here starts the html (only title)  -->
	<h1>TITOLO</h1>

	<!-- here starts the script to add input("question", "answer") generated by add_questions() in python -->
	<script>
			"""
	# creates all the input("question", "answer") string
	html += add_questions(lista_domande)
	# close the script tag
	html += "</script>"
	html = html.replace("TITOLO", title)
	with open(f"{filename}.html", "w", encoding="utf-8") as file:
		file.write(html)
	os.startfile(f"{filename}.html")




# ===== Customize your quiz ================== >>>

'''
the sign '#' in the question puts a list of possible answers
the sign '#' in the answer puts alternative right answers
'''


filename = "capitals1"
title = "Capitals quiz nr. 1"
lista_domande = [
# "question", "answer#another right answer#..."
	["Chi sono i principali soggetti in disavanzo?", "imprese"],
	["La banca ha la sua principale attività nell'intermediazione ...c", "creditizia"],
	[]
]

# ==================== END customization =============== !!!

start()